version: 2
updates:
- package-ecosystem: gomod
  directory: /
  patterns:
  - '*'
  multi-ecosystem-group: routine
- package-ecosystem: gomod
  directory: /desktop
  patterns:
  - '*'
  multi-ecosystem-group: routine
- package-ecosystem: github-actions
  directory: /
  patterns:
  - '*'
  multi-ecosystem-group: routine
multi-ecosystem-groups:
  routine:
    schedule:
      interval: weekly
