// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/web/apitypes — DO NOT EDIT.
// Regenerate with: make web-types

//////////
// source: apitypes.go
/*
Package apitypes defines the JSON wire contract for the web SPA's /api/*
endpoints. It is the single source of truth: the Go handlers (internal/web)
marshal these structs, and tygo generates the TypeScript types from this file
(internal/web/frontend/src/lib/api-types.ts) — so the front-end and back-end
can't drift. It is a pure data package (no imports) so codegen stays trivial.
*/

/**
 * State is GET /api/state — capabilities + headline counts for the shell.
 */
export interface State {
  canEdit: boolean;
  csrf: string; // echo as X-CSRF on writes; "" when read-only
  version: string;
  openCount: number /* int */;
  noteCount: number /* int */;
  sources: string[];
  warning?: string; // non-empty when the store couldn't be fully read
}
/**
 * NoteLink is a link to a note (sidebar index, search results, prev/next).
 */
export interface NoteLink {
  url: string;
  title: string;
  path: string;
}
/**
 * TreeNode is one entry in the sidebar's folder/note tree.
 */
export interface TreeNode {
  name: string;
  path: string; // folder key; "" for notes
  url: string;
  isNote: boolean;
  children?: TreeNode[];
}
/**
 * NotesIndex is GET /api/notes — the tree plus a flat index.
 */
export interface NotesIndex {
  tree: TreeNode[];
  index: NoteLink[];
}
/**
 * Task is one todo.txt task projected for the UI.
 */
export interface Task {
  id: string;
  text: string;
  status: string;
  due?: string;
  source?: string;
  project?: string;
  tags?: string[];
  blocker?: string;
}
/**
 * TaskGroup is tasks bucketed by status (open/doing/blocked/done).
 */
export interface TaskGroup {
  status: string;
  tasks: Task[];
}
/**
 * TasksResponse is GET /api/tasks and the body returned by task writes.
 */
export interface TasksResponse {
  groups: TaskGroup[];
}
/**
 * Backlink is one "Linked from" entry on a note page.
 */
export interface Backlink {
  title: string;
  url: string;
  text: string;
  isNote: boolean;
}
/**
 * TaskRef is one task that references a note (the task↔note moat).
 */
export interface TaskRef {
  text: string;
  status: string;
  source: string;
}
/**
 * NoteView is GET /api/notes/{handle} — the fully rendered note page.
 */
export interface NoteView {
  id: string;
  title: string;
  folder: string;
  file: string;
  crumbs: string[];
  source: string;
  created: string;
  tags: string[];
  bodyHTML: string;
  backlinks: Backlink[];
  taskRefs: TaskRef[];
  prev?: NoteLink;
  next?: NoteLink;
  etag: string;
}
/**
 * RawNote is GET /api/notes/{handle}/raw — the on-disk text + its validator.
 */
export interface RawNote {
  text: string;
  etag: string;
}
/**
 * ActivityEvent is one item in the activity feed (When is RFC3339).
 */
export interface ActivityEvent {
  when: string;
  action: string;
  kind: string;
  source: string;
  title: string;
  url?: string;
}
/**
 * ActivityDay groups events under a calendar date.
 */
export interface ActivityDay {
  date: string;
  events: ActivityEvent[];
}
/**
 * ActivityResponse is GET /api/activity.
 */
export interface ActivityResponse {
  days: ActivityDay[];
  sources: string[];
}
/**
 * SearchResult is one ranked search hit: title matches rank first (no snippet),
 * body matches carry the matching line as a snippet for context.
 */
export interface SearchResult {
  url: string;
  title: string;
  path: string;
  snippet?: string; // matching line (body hits only)
}
/**
 * SearchResponse is GET /api/search.
 */
export interface SearchResponse {
  results: SearchResult[];
  truncated?: boolean; // more matched than were returned
}
/**
 * Tag is one entry in the tag vocabulary with its usage count.
 */
export interface Tag {
  name: string;
  count: number /* int */;
}
/**
 * TagsResponse is GET /api/tags.
 */
export interface TagsResponse {
  tags: Tag[];
}
/**
 * OrphansResponse is GET /api/orphans — notes with no links in or out.
 */
export interface OrphansResponse {
  notes: NoteLink[];
}
/**
 * GraphNode is one entity in the knowledge graph (Deg = link degree, for sizing).
 */
export interface GraphNode {
  id: string;
  kind: string; // "note" | "task"
  title: string;
  url: string;
  folder: string;
  source: string;
  tags: string[];
  deg: number /* int */;
}
/**
 * GraphLink is one wikilink edge as a pair of indices into GraphData.Nodes.
 */
export interface GraphLink {
  s: number /* int */;
  t: number /* int */;
}
/**
 * GraphData is GET /api/graph — the note↔note wikilink graph.
 */
export interface GraphData {
  nodes: GraphNode[];
  links: GraphLink[];
  truncated?: boolean; // capped to the most-connected nodes (E4)
}
/**
 * CreatedNote is the result of POST /api/notes — the new note's stable handle
 * and its URL, so the client can navigate straight to it.
 */
export interface CreatedNote {
  handle: string;
  url: string;
}
/**
 * JournalDay is one existing daily note (date + the note's stable handle).
 */
export interface JournalDay {
  date: string; // YYYY-MM-DD
  handle: string; // note handle, for the note view
}
/**
 * JournalResponse is GET /api/journal — the daily-notes index for the journal UI.
 */
export interface JournalResponse {
  today: string; // today's date in the server's local time
  folder: string; // subfolder daily notes live under (e.g. "journal")
  days: JournalDay[]; // existing daily notes, newest first
}
